name: innovino_${TARGET}
services:
  frontend:
    container_name: ${TARGET}-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${TARGET}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  backend:
    container_name: ${TARGET}-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${TARGET}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:18
    env_file:
      - ./backend/.env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:

networks:
  default:
    external: true
    name: caddy